# Generated by Django 4.2.7 on 2023-11-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_dish', verbose_name='фото еды')),
                ('title', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('descriptions', models.TextField(verbose_name='Описание блюда')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('сlever_words', models.CharField(max_length=255, verbose_name='умные слова')),
            ],
            options={
                'verbose_name': ('Меню',),
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
