# Generated by Django 4.2.7 on 2023-11-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='сlever_words',
        ),
    ]
