# Generated by Django 4.2.7 on 2023-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_menu_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_cook', verbose_name='фото повара')),
                ('name', models.CharField(max_length=255, verbose_name='имя повара')),
                ('rank', models.CharField(max_length=255, verbose_name='звание повара')),
                ('description', models.CharField(max_length=255, verbose_name='слова повара')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ссылка на Youtube')),
            ],
        ),
    ]
