# Generated by Django 4.2.7 on 2023-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_chefs_clients_cooking_experience_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'опыт', 'verbose_name_plural': 'опыт'},
        ),
    ]
