# Generated by Django 4.2.7 on 2023-11-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_all_desserts_dinner_restuarant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
    ]
