# Generated by Django 4.2.7 on 2023-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_all', verbose_name='все блюда')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('name', models.CharField(max_length=255, verbose_name='название блюды')),
            ],
            options={
                'verbose_name': 'все блюда',
                'verbose_name_plural': 'все блюда',
            },
        ),
        migrations.DeleteModel(
            name='Desserts',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Restuarant',
        ),
    ]
