# Generated by Django 4.2.7 on 2023-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_gallery_delete_desserts_delete_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description2',
            field=models.CharField(default=1, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='description3',
            field=models.CharField(default=1, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='description4',
            field=models.CharField(default=1, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(default=1, upload_to='image_dessert', verbose_name='дессерт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(default=1, upload_to='image_all', verbose_name='ресторан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(default=1, upload_to='image_all', verbose_name='ужин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='name2',
            field=models.CharField(default=1, max_length=255, verbose_name='название блюды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='name3',
            field=models.CharField(default=1, max_length=255, verbose_name='название блюды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='name4',
            field=models.CharField(default=1, max_length=255, verbose_name='название блюды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='image_gallery', verbose_name='все блюда'),
        ),
    ]
